import React from 'react';
import {ArrowRight,ArrowUpRight} from 'lucide-react';
import {useCms,isPublic} from '../context/CmsContext';
export const Home:React.FC<{navigate:(u:string)=>void}>=({navigate})=>{const{site,projects,posts,activities,journey}=useCms();const p=projects.filter(isPublic).slice(0,4), po=posts.filter(isPublic).slice(0,3), a=activities.filter(isPublic).slice(0,3), j=journey.filter(x=>x.isPublished!==false).sort((x,y)=>(x.sortOrder||0)-(y.sortOrder||0)).slice(-4);return <>
<section className="home-hero"><div className="shell home-hero-grid"><div><div className="eyebrow">{site.homepageBadge}</div><h1>{site.siteName}</h1><p className="home-tagline">{site.tagline}</p><p className="home-intro">{site.intro}</p><div className="button-row"><a className="button primary" href="/gioi-thieu" onClick={e=>{e.preventDefault();navigate('/gioi-thieu')}}>Giới thiệu <ArrowRight size={16}/></a><a className="button secondary" href="/du-an" onClick={e=>{e.preventDefault();navigate('/du-an')}}>Xem dự án</a></div></div><aside className="now-card"><div className="now-kicker">NOW</div><h2>{site.nowTitle}</h2><p>{site.nowText}</p><a href="/now" onClick={e=>{e.preventDefault();navigate('/now')}}>Xem trang Now <ArrowUpRight size={15}/></a></aside></div></section>
<section className="home-strip"><div className="shell"><div className="strip-label">Đang xây</div><div className="project-list">{p.map(x=><a key={x.id} href={`/du-an/${x.slug}`} onClick={e=>{e.preventDefault();navigate(`/du-an/${x.slug}`)}}><span>{x.title}</span><small>{x.summary}</small><ArrowUpRight size={18}/></a>)}</div></div></section>
{j.length>0&&<section className="home-section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Selected timeline</div><h2>Một vài dấu mốc</h2></div><a href="/hanh-trinh" onClick={e=>{e.preventDefault();navigate('/hanh-trinh')}}>Toàn bộ hành trình</a></div><div className="timeline compact">{j.map(x=><article key={x.id}><span>{x.dateLabel}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>}
<section className="home-section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Latest</div><h2>Mới viết</h2></div><a href="/bai-viet" onClick={e=>{e.preventDefault();navigate('/bai-viet')}}>Tất cả bài viết</a></div><div className="editorial-list">{po.map(x=><a key={x.id} href={`/bai-viet/${x.slug}`} onClick={e=>{e.preventDefault();navigate(`/bai-viet/${x.slug}`)}}><div><span>{x.category||'Bài viết'}</span><h3>{x.title}</h3><p>{x.summary}</p></div><ArrowUpRight/></a>)}</div></div></section>
{a.length>0&&<section className="home-section"><div className="shell"><div className="section-head"><h2>Hoạt động gần đây</h2><a href="/hoat-dong" onClick={e=>{e.preventDefault();navigate('/hoat-dong')}}>Xem thêm</a></div><div className="feed-grid">{a.map(x=><a className="feed-card" key={x.id} href={`/hoat-dong/${x.slug}`} onClick={e=>{e.preventDefault();navigate(`/hoat-dong/${x.slug}`)}}><div className="feed-meta">{x.date}</div><h3>{x.title}</h3><p>{x.summary}</p></a>)}</div></div></section>}
</>}
