import React from 'react';
import {ArrowRight,ArrowUpRight,Sparkles,Layers3,PenTool,Globe2,BriefcaseBusiness,Images} from 'lucide-react';
import {useCms,isPublic} from '../context/CmsContext';
export const Home:React.FC<{navigate:(u:string)=>void}>=({navigate})=>{
 const{site,projects,posts,activities,journey}=useCms();
 const p=projects.filter(isPublic).slice(0,4),po=posts.filter(isPublic).slice(0,3),a=activities.filter(isPublic).slice(0,3),j=journey.filter(x=>x.isPublished!==false).sort((x,y)=>(x.sortOrder||0)-(y.sortOrder||0)).slice(-4);
 const visuals=[...projects.filter(isPublic).filter(x=>x.featuredImage).map(x=>({url:x.featuredImage!,alt:x.featuredImageAlt||x.title})),...activities.filter(isPublic).flatMap(x=>[...(x.featuredImage?[{url:x.featuredImage,alt:x.featuredImageAlt||x.title}]:[]),...(x.gallery||[]).map(g=>({url:g.url,alt:g.alt||x.title}))])].slice(0,5);
 const go=(u:string,e:React.MouseEvent)=>{e.preventDefault();navigate(u)};
 return <>
 <section className="home-hero portrait-hero"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-ring ring-one"/><div className="hero-ring ring-two"/><div className="shell home-hero-grid">
  <div className="hero-copy reveal"><div className="eyebrow"><Sparkles size={13}/> {site.homepageBadge||'KHÔNG GIAN CÁ NHÂN'}</div><h1><span>Bui</span> <span className="gradient-word">Loc</span></h1><p className="home-tagline">{site.tagline}</p><p className="home-intro">{site.intro}</p><div className="button-row"><a className="button primary magnetic" href="/gioi-thieu" onClick={e=>go('/gioi-thieu',e)}>Khám phá câu chuyện <ArrowRight size={16}/></a><a className="button secondary" href="/du-an" onClick={e=>go('/du-an',e)}>Xem dự án</a></div><div className="hero-chips"><span>Giáo dục</span><span>Cộng đồng</span><span>Sản phẩm số</span></div></div>
  <aside className="now-card spotlight-card reveal delay-1"><div className="now-kicker">NOW · 2026</div><h2>{site.nowTitle}</h2><p>{site.nowText}</p><a href="/now" onClick={e=>go('/now',e)}>Xem mình đang làm gì <ArrowUpRight size={15}/></a><div className="card-sheen"/></aside>
 </div><div className="hero-signature" aria-hidden="true">BUI LOC · HỒ SƠ CÁ NHÂN · 2026</div><div className="scroll-cue"><span>KHÁM PHÁ</span><i/></div></section>
 <section className="kinetic-marquee" aria-label="Chủ đề"><div className="marquee-track"><span>GIÁO DỤC</span><i>✦</i><span>CỘNG ĐỒNG</span><i>✦</i><span>SẢN PHẨM SỐ</span><i>✦</i><span>CÔNG VIỆC SÁNG TẠO</span><i>✦</i><span>GIÁO DỤC</span><i>✦</i><span>CỘNG ĐỒNG</span><i>✦</i><span>SẢN PHẨM SỐ</span><i>✦</i><span>CÔNG VIỆC SÁNG TẠO</span><i>✦</i></div></section>
 <section className="identity-bento home-section"><div className="shell"><div className="section-head reveal"><div><div className="eyebrow">Hồ sơ cá nhân</div><h2>Một nơi gom những điều mình đang xây.</h2></div></div><div className="bento-grid">
  <a className="bento-card bento-large reveal" href="/gioi-thieu" onClick={e=>go('/gioi-thieu',e)}><Globe2/><span>01 · Chân dung</span><h3>Tôi là ai?</h3><p>Một góc để kể rõ hơn về cách mình học, làm, thử nghiệm và phát triển những ý tưởng có ích.</p><ArrowUpRight/></a>
  <a className="bento-card reveal delay-1" href="/du-an" onClick={e=>go('/du-an',e)}><Layers3/><span>02 · Dự án</span><h3>Những thứ đang xây</h3><p>Dự án, sản phẩm số và các thử nghiệm được cập nhật theo thời gian.</p></a>
  <a className="bento-card reveal delay-2" href="/bai-viet" onClick={e=>go('/bai-viet',e)}><PenTool/><span>03 · Bài viết</span><h3>Góc viết</h3><p>Ghi lại suy nghĩ, kinh nghiệm và những điều đáng nhớ.</p></a>
 </div></div></section>
 {p.length>0&&<section className="home-strip dark-strip"><div className="shell"><div className="section-head reveal"><div><div className="eyebrow">Dự án chọn lọc</div><h2>Dự án nổi bật</h2></div><a href="/du-an" onClick={e=>go('/du-an',e)}>Tất cả dự án</a></div><div className="project-list">{p.map((x,i)=><a className="reveal" key={x.id} href={`/du-an/${x.slug}`} onClick={e=>go(`/du-an/${x.slug}`,e)}><b>0{i+1}</b><span>{x.title}</span><small>{x.summary}</small><ArrowUpRight size={18}/></a>)}</div></div></section>}
 {j.length>0&&<section className="home-section timeline-section"><div className="shell"><div className="section-head reveal"><div><div className="eyebrow">Hành trình</div><h2>Một vài dấu mốc</h2></div><a href="/hanh-trinh" onClick={e=>go('/hanh-trinh',e)}>Toàn bộ hành trình</a></div><div className="timeline compact">{j.map((x,i)=><article className="reveal" key={x.id}><i className="timeline-index">{String(i+1).padStart(2,'0')}</i><span>{x.dateLabel}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>}
 <section className="home-section"><div className="shell"><div className="section-head reveal"><div><div className="eyebrow">Bài viết mới</div><h2>Mới viết</h2></div><a href="/bai-viet" onClick={e=>go('/bai-viet',e)}>Tất cả bài viết</a></div><div className="editorial-list">{po.map((x,i)=><a className="reveal" key={x.id} href={`/bai-viet/${x.slug}`} onClick={e=>go(`/bai-viet/${x.slug}`,e)}><b>{String(i+1).padStart(2,'0')}</b><div><span>{x.category||'Bài viết'}</span><h3>{x.title}</h3><p>{x.summary}</p></div><ArrowUpRight/></a>)}</div></div></section>
 <section className="home-section home-services-preview"><div className="shell"><div className="section-head reveal"><div><div className="eyebrow">Dịch vụ · Tư vấn · Hỗ trợ 0đ</div><h2>Có việc cần làm, có điều cần góp ý.</h2></div><a href="/dich-vu" onClick={e=>go('/dich-vu',e)}>Khám phá dịch vụ</a></div><div className="service-preview-grid"><a className="service-preview-main reveal" href="/dich-vu" onClick={e=>go('/dich-vu',e)}><BriefcaseBusiness/><span>CÓ PHÍ · TƯ VẤN · HỖ TRỢ 0Đ</span><h3>Từ website, nội dung đến góp ý dự án và hỗ trợ miễn phí khi phù hợp.</h3><p>Nhận làm theo phạm vi cụ thể, tư vấn cách triển khai và dành một phần thời gian cho các yêu cầu 0đ phù hợp với người trẻ, giáo dục và cộng đồng.</p><b>Xem cách mình làm <ArrowUpRight size={16}/></b></a><div className="service-preview-side reveal delay-1"><span>01</span><b>Rõ mục tiêu</b><span>02</span><b>Rõ phạm vi</b><span>03</span><b>Rõ bàn giao</b></div></div></div></section>
 {visuals.length>0&&<section className="home-section home-visual-preview"><div className="shell"><div className="section-head reveal"><div><div className="eyebrow">Thư viện hình ảnh</div><h2>Những khung hình đang được lưu lại.</h2></div><a href="/thu-vien" onClick={e=>go('/thu-vien',e)}>Mở thư viện <Images size={15}/></a></div><div className="visual-preview-grid">{visuals.map((x,i)=><a href="/thu-vien" onClick={e=>go('/thu-vien',e)} className={`visual-preview v${i}`} key={`${x.url}-${i}`}><img src={x.url} alt={x.alt} loading="lazy"/></a>)}</div></div></section>}
 {a.length>0&&<section className="home-section activity-section"><div className="shell"><div className="section-head reveal"><div><div className="eyebrow">Hoạt động</div><h2>Hoạt động gần đây</h2></div><a href="/hoat-dong" onClick={e=>go('/hoat-dong',e)}>Xem thêm</a></div><div className="feed-grid">{a.map(x=><a className="feed-card reveal" key={x.id} href={`/hoat-dong/${x.slug}`} onClick={e=>go(`/hoat-dong/${x.slug}`,e)}><div className="feed-meta">{x.date}</div><h3>{x.title}</h3><p>{x.summary}</p><span>Xem chi tiết <ArrowUpRight size={14}/></span></a>)}</div></div></section>}
 </>
}
